# Generated by Django 4.2.5 on 2024-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_profile_email_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("family_structure", "Family Structure"),
                            ("socioeconomic_status", "Socioeconomic Status"),
                            ("geographical_background", "Geographical Background"),
                            ("educational_background", "Educational Background"),
                            (
                                "cultural_and_ethnic_identity",
                                "Cultural And Ethnic Identity",
                            ),
                            ("religious_background", "Religious Background"),
                            ("health", "Health"),
                            ("language", "Language"),
                            ("work_experience", "Work Experience"),
                            ("mental_health", "Mental Health"),
                        ],
                        max_length=100,
                    ),
                ),
                ("detail", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WantsNeeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="background",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.background"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="character_traits",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.charactertrait"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.hobby"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.skill"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.subject"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="wants_needs",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="account.wantsneeds"
            ),
        ),
    ]
