# Generated by Django 4.2.5 on 2024-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_submissions_count_delete_userrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submissions_count',
            field=models.IntegerField(default=0),
        ),
    ]
